### PR TITLE
	Adequate rolling

### PR DESCRIPTION
**Pull request by dmitrii-ubskii**
+ multiple dice commands (e.g. "2d20+2d8")
+ simple arithmetic (+-*/)
+ parentheses
- tested locally, not tested on discord, possible integration issues

### CODE REVIEW

**Comment by Carbsta** [comment]
This is quite a bit of extra code for some extra rolling features. I really want to update the dice rolling on the bot, but is using Re really the best way? Atm the bot already uses more memory than ideal, so the most efficient solutions are appreciated. Thanks for the help and feedback anyway, I'll review the code, possibly make some changes then let you know.

**Comment by dmitrii-ubskii** [comment]
It's the cleanest solution I can see. Also, I suspect just doing it manually would be much worse for performance, even if better for memory.

Consider moving regexes to static class fields and precompiling them, if that's much of an issue.

As for size of the commit — with this solution it's easier, I believe, to include more dice formulae e.g. rerolls and drops (e.g. "2d20r1" and "4d6d1")

**Comment by dmitrii-ubskii** [comment]
So how about it? I would really appreciate being able to roll 2d6+2 in discord.

**Comment by Carbsta** [comment]
sorry for not responding, atm you currently can do 2d6+2 in discord, and 2d6 +2 as well using the current roll functionality. Since I had already implemented that feature, doing more roll features wasn't a big priority for me and I have been very busy last week. Better rolling with multiplication and division will be coming soon, but you already can do basic arithmetic.
First I am going to implement a help command, so people can see how to use the roll command since a lot of users don't seem to realise addition works.

**Comment by dmitrii-ubskii** [comment]
Unless you've changed it since Sunday (and you haven't), no I can't. It will roll separately and add modifier to each, outputting 1d6+2, 1d6+2. 

I mean, sure I can subtract modifier from the total, but that is less than ideal and requires one to actually notice what it does.

**Comment by Carbsta** [comment]
Actually no, typing ?roll 2d6 +2 should produce the affect you are after.
Try it. The space is important. I should probably changed the syntax to use
brackets instead.

**Pull request closed without merging**
